name: build.on.push

on: [push]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    env:
      src-directory: ./src
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore
        working-directory: ${{ env.src-directory }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.src-directory }}
        run: > 
          dotnet build --configuration Release --no-restore 
          /property:GenerateFullPaths=true 
          
      - name: Pack
        working-directory: ${{ env.src-directory }}
        run: > 
          dotnet pack --configuration Release --no-restore
