name: publish

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      src-directory: ./src
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: Restore
        working-directory: ${{ env.src-directory }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.src-directory }}
        run: >
          dotnet build --configuration Release --no-restore 
          /property:GenerateFullPaths=true
          /property:Version=${VERSION}

      - name: Pack
        working-directory: ${{ env.src-directory }}
        run: >
          dotnet pack --configuration Release --no-restore
          /property:Version=${VERSION}

      - name: Publish
        working-directory: ${{ env.src-directory }}
        run: >
          nuget push **\*.nupkg
          -NoSymbols
          -Source 'https://api.nuget.org/v3/index.json' 
          -ApiKey ${{secrets.NUGET_API_KEY}}
